app:
  name: svc
  image:
    repository: "onecx/onecx-human-task-svc"
  db:
    enabled: true
  operator:
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-ht:read, ocx-ht:write ]
    microservice:
      spec:
        description: "OneCX Human Task backend service"
        name: "onecx-human-task-svc"